# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='no',
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='yes',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='option',
            field=models.CharField(choices=[(b'YES', b'Yes, I am'), (b'NO', b'No, I am not')], default=b'YES', max_length=10),
        ),
    ]
