# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0002_auto_20180317_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsvp',
            options={'ordering': ['first_name']},
        ),
        migrations.RenameField(
            model_name='rsvp',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='last_name',
            field=models.CharField(default=b'surname', max_length=50),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='option',
            field=models.CharField(choices=[(b'YES', b'YES'), (b'NO', b'NO')], default=b'YES', max_length=10),
        ),
    ]
