# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0003_auto_20180317_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
