# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-21 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0004_auto_20180317_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rsvp',
            old_name='option',
            new_name='will_be_present',
        ),
    ]
