# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvpapp', '0005_auto_20180322_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='email',
            field=models.EmailField(default=b'yemi.oa@gmail.com', max_length=50),
        ),
    ]
